wmauda: Fix installation dir
I'd get this:

Pilar:/home/mafra/git-repos/dockapps/wmauda-0.8 # make install
install -d /usr/local/bin
install -d /usr/local/share/pixmaps
install -d /usr/local/share/man/man1
install -m 0755 wmauda /usr/local/bin
install -m 0644 wmauda.xpm /usr/local/share/pixmaps
install -m 0644 wmauda.1 /usr/local/share/man/man1

[mafra@Pilar:wmauda-0.8]$ wmauda
ERROR: Couldn't find /usr/share/pixmaps/wmauda.xpm

So change the hardcoded installation prefix to be just /usr
instead of /usr/local