wmget: Remove docbook -> manpage conversion.
It was resulting in compilation errors:
   profzoom@cayke:~/src/dockapps/dockapps/wmget$ xsltproc --nonet
     wmget.refentry.xml
   I/O error : Attempt to load network entity http://docbook.sourceforge.net/
     release/xsl/1.62/manpages/docbook.xsl
   warning: failed to load external entity "http://docbook.sourceforge.net/
     release/xsl/1.62/manpages/docbook.xsl"
   error
   xsltParseStylesheetFile : cannot parse http://docbook.sourceforge.net/
     release/xsl/1.62/manpages/docbook.xsl
   compilation error: file wmget.refentry.xml line 19 element refentry
   xsltParseStylesheetProcess : document is not a stylesheet

We therefore remove the xml source file and in the future, we will edit the
troff file directly.

We also add the version number to the manpage via autoconf.